services:
  rabbitmq:
    image: bitnami/rabbitmq:latest
    container_name: rabbitmq
    ports:
    - 5672:5672
    - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "rabbit"
      RABBITMQ_DEFAULT_PASS: "rabbit"
    networks:
      - app-network
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: wallet
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
    - 8091:80
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USER: rabbit
      RABBIT_PASSWORD: rabbit
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
